### ISSUE TITLE
missing states & nodes

### ISSUE THREAD

**Issue by simonhrjohnson** [isTravis/fiftynifty#102]
I invited Jess H and her map shows that she has instigated calls in three states: NY, MA, and VT

However, I did not get credit for NY

And Jess H (a DC resident) did not make any calls herself and, according to the family tree, only invited Jane (who made the calls in VT)

So our family trees do not show who made the calls in MA and NY for her

Also, Jess reports that she got someone in VA to make a call.  There is no record of this at all

**Comment by simonhrjohnson** [comment]
Looking in more detail -- there are two people showing in Jess H's family tree who do not have "invited by Jess H" when I click on them.  (The third person, in VT, does show this -- and credit flows back up to me)

Jess H may be inviting via Facebook.  Could this be part of the issue?

**Comment by simonhrjohnson** [comment]
Further clarification: Jess H is getting credit for all three states, and my previous comment is now wrong -- all three people show as invited by Jess H

But I (as the person who invited Jess H) am not getting credit for NY .

**Comment by jasrub** [comment]
The issue is actually because I manually updated Jess H to be invited by you, and did a mistake while doing that.
The third person in VT joined after I made the change with mistake - so looks fine and flows back to you. 
I just manually fixed that, but it will take a little bit of time to update in the cache so you should see the change as well.

Also, Jess H invited 6 people, including one person (Jen) in VA, but Jen and 2 other users (Katie and Kristen) never verified their phone number on login, so they are not registered as users and Jess don't see them in her tree (they also couldn't make any calls)

**Comment by simonhrjohnson** [comment]
Thanks!
