### ISSUE TITLE
Landing Page design is missing call to action

### ISSUE THREAD

**Issue by jasrub** [isTravis/fiftynifty#74]
Missing call to action - the invite text looks like the titles and it's not clear. should be inside the join box:
![screenshot_20170217-102255](https://cloud.githubusercontent.com/assets/8539148/23072404/8c2a6322-f4ff-11e6-9b12-af7abba2d5fa.png)
The user should see the join box (or at least a button that scrolls there) without needing to scroll

Also the background image repeats , which doesn't look good. 
![screenshot_20170217-102318](https://cloud.githubusercontent.com/assets/8539148/23072436/abdafb96-f4ff-11e6-8dc6-4d804c9a4cde.png)

If you are signed in - the background color is cut. And this is also missing the call to action on first view
![screenshot_20170217-102411](https://cloud.githubusercontent.com/assets/8539148/23072451/b50cf1f6-f4ff-11e6-9af2-316bd3896783.png)

**Comment by ABLippman** [comment]
This issue is MAJOR.  I'm getting the same complaint from testers/users:

Here is what people told me.
 
1. People don't think they would know what to say.  A standard script would be better.  I think there is something now but only show after. 
2. Email to long.  --  I shouldn't have sent such a long email.  Not many people reads long emails.   If you put on a blog post or on medium then easy to tweet about and share.  Margaux (my sister) literally took screenshot of email box and asked if it was spam.    
3.  The sequential user ids bother people because to easy to enumerate all users.  Can you switch to slightly more random id generator for share?  (I agree it is just nickname people put, but then they wonder what else isn't secure.). One of my friends signed up under Steve Zwick because he was playing around with numbers.   Can you re-assing 328 to me?
4.  Time of day - People not sure if they can do after work.   Need to make clear you will most likely be leaving voicemail.  
5.  The UX could use some work.  For example call to action below fold on mobile at least.

**Comment by isTravis** [comment]
Fixed by @lemeb or @jasrub
